// GENERATED BY CONSOLIDATION SCRIPT

// Contains all V2 protocol types in a single file



import type { JsonValue } from "../serde_json/JsonValue";



// Stubs for missing external types

export type AbsolutePathBuf = string;

export type ReasoningEffort = string;

export type PlanType = string;

export type Resource = any;

export type ResourceTemplate = any;

export type Tool = any;

export type ReasoningSummary = string;

export type Verbosity = string;

export type WebSearchMode = string;

export type InputModality = string;

export type ResponseItem = any;

export type AuthMode = string;

export type SubAgentSource = any;

export type CollaborationMode = any;

export type Personality = any;

export type ForcedLoginMethod = string;



export type Account = { "type": "apiKey", } | { "type": "chatgpt", email: string, planType: PlanType, };

export type AccountLoginCompletedNotification = { loginId: string | null, success: boolean, error: string | null, };

export type AccountRateLimitsUpdatedNotification = { rateLimits: RateLimitSnapshot, };

export type AccountUpdatedNotification = { authMode: AuthMode | null, };

export type AgentMessageDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, };

export type AnalyticsConfig = { enabled: boolean | null, } & ({ [key in string]?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null });

/**
 * EXPERIMENTAL - app metadata returned by app-list APIs.
 */
export type AppBranding = { category: string | null, developer: string | null, website: string | null, privacyPolicy: string | null, termsOfService: string | null, isDiscoverableApp: boolean, };

export type AppDisabledReason = "unknown" | "user";

/**
 * EXPERIMENTAL - app metadata returned by app-list APIs.
 */
export type AppInfo = { id: string, name: string, description: string | null, logoUrl: string | null, logoUrlDark: string | null, distributionChannel: string | null, branding: AppBranding | null, appMetadata: AppMetadata | null, labels: { [key in string]?: string } | null, installUrl: string | null, isAccessible: boolean, 
/**
 * Whether this app is enabled in config.toml.
 * Example:
 * ```toml
 * [apps.bad_app]
 * enabled = false
 * ```
 */
isEnabled: boolean, };

/**
 * EXPERIMENTAL - notification emitted when the app list changes.
 */
export type AppListUpdatedNotification = { data: Array<AppInfo>, };

export type AppMetadata = { review: AppReview | null, categories: Array<string> | null, subCategories: Array<string> | null, seoDescription: string | null, screenshots: Array<AppScreenshot> | null, developer: string | null, version: string | null, versionId: string | null, versionNotes: string | null, firstPartyType: string | null, firstPartyRequiresInstall: boolean | null, showInComposerWhenUnlinked: boolean | null, };

export type AppReview = { status: string, };

export type AppScreenshot = { url: string | null, fileId: string | null, userPrompt: string, };

export type AppsConfig = { [key in string]?: { enabled: boolean, disabled_reason: AppDisabledReason | null, } };

/**
 * EXPERIMENTAL - list available apps/connectors.
 */
export type AppsListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null, 
/**
 * Optional thread id used to evaluate app feature gating from that thread's config.
 */
threadId?: string | null, 
/**
 * When true, bypass app caches and fetch the latest data from sources.
 */
forceRefetch?: boolean, };

/**
 * EXPERIMENTAL - app list response.
 */
export type AppsListResponse = { data: Array<AppInfo>, 
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * If None, there are no more items to return.
 */
nextCursor: string | null, };

export type AskForApproval = "untrusted" | "on-failure" | "on-request" | "never";

export type ByteRange = { start: number, end: number, };

export type CancelLoginAccountParams = { loginId: string, };

export type CancelLoginAccountResponse = { status: CancelLoginAccountStatus, };

export type CancelLoginAccountStatus = "canceled" | "notFound";

export type ChatgptAuthTokensRefreshParams = { reason: ChatgptAuthTokensRefreshReason, 
/**
 * Workspace/account identifier that Codex was previously using.
 *
 * Clients that manage multiple accounts/workspaces can use this as a hint
 * to refresh the token for the correct workspace.
 *
 * This may be `null` when the prior auth state did not include a workspace
 * identifier (`chatgpt_account_id`).
 */
previousAccountId?: string | null, };

export type ChatgptAuthTokensRefreshReason = "unauthorized";

export type ChatgptAuthTokensRefreshResponse = { accessToken: string, chatgptAccountId: string, chatgptPlanType: string | null, };

/**
 * This translation layer make sure that we expose codex error code in camel case.
 *
 * When an upstream HTTP status is available (for example, from the Responses API or a provider),
 * it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.
 */
export type CodexErrorInfo = "contextWindowExceeded" | "usageLimitExceeded" | "serverOverloaded" | { "httpConnectionFailed": { httpStatusCode: number | null, } } | { "responseStreamConnectionFailed": { httpStatusCode: number | null, } } | "internalServerError" | "unauthorized" | "badRequest" | "threadRollbackFailed" | "sandboxError" | { "responseStreamDisconnected": { httpStatusCode: number | null, } } | { "responseTooManyFailedAttempts": { httpStatusCode: number | null, } } | "other";

export type CollabAgentState = { status: CollabAgentStatus, message: string | null, };

export type CollabAgentStatus = "pendingInit" | "running" | "completed" | "errored" | "shutdown" | "notFound";

export type CollabAgentTool = "spawnAgent" | "sendInput" | "resumeAgent" | "wait" | "closeAgent";

export type CollabAgentToolCallStatus = "inProgress" | "completed" | "failed";

export type CommandAction = { "type": "read", command: string, name: string, path: string, } | { "type": "listFiles", command: string, path: string | null, } | { "type": "search", command: string, query: string | null, path: string | null, } | { "type": "unknown", command: string, };

export type CommandExecParams = { command: Array<string>, timeoutMs?: number | null, cwd?: string | null, sandboxPolicy?: SandboxPolicy | null, };

export type CommandExecResponse = { exitCode: number, stdout: string, stderr: string, };

export type CommandExecutionApprovalDecision = "accept" | "acceptForSession" | { "acceptWithExecpolicyAmendment": { execpolicy_amendment: ExecPolicyAmendment, } } | "decline" | "cancel";

export type CommandExecutionOutputDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, };

export type CommandExecutionRequestApprovalParams = { threadId: string, turnId: string, itemId: string, 
/**
 * Unique identifier for this specific approval callback.
 *
 * For regular shell/unified_exec approvals, this is null.
 *
 * For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to
 * one parent `itemId`, so `approvalId` is a distinct opaque callback id
 * (a UUID) used to disambiguate routing.
 */
approvalId?: string | null, 
/**
 * Optional explanatory reason (e.g. request for network access).
 */
reason?: string | null, 
/**
 * The command to be executed.
 */
command?: string | null, 
/**
 * The command's working directory.
 */
cwd?: string | null, 
/**
 * Best-effort parsed command actions for friendly display.
 */
commandActions?: Array<CommandAction> | null, 
/**
 * Optional proposed execpolicy amendment to allow similar commands without prompting.
 */
proposedExecpolicyAmendment?: ExecPolicyAmendment | null, };

export type CommandExecutionRequestApprovalResponse = { decision: CommandExecutionApprovalDecision, };

export type CommandExecutionStatus = "inProgress" | "completed" | "failed" | "declined";

export type Config = {model: string | null, review_model: string | null, model_context_window: bigint | null, model_auto_compact_token_limit: bigint | null, model_provider: string | null, approval_policy: AskForApproval | null, sandbox_mode: SandboxMode | null, sandbox_workspace_write: SandboxWorkspaceWrite | null, forced_chatgpt_workspace_id: string | null, forced_login_method: ForcedLoginMethod | null, web_search: WebSearchMode | null, tools: ToolsV2 | null, profile: string | null, profiles: { [key in string]?: ProfileV2 }, instructions: string | null, developer_instructions: string | null, compact_prompt: string | null, model_reasoning_effort: ReasoningEffort | null, model_reasoning_summary: ReasoningSummary | null, model_verbosity: Verbosity | null, analytics: AnalyticsConfig | null} & ({ [key in string]?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null });

export type ConfigBatchWriteParams = { edits: Array<ConfigEdit>, 
/**
 * Path to the config file to write; defaults to the user's `config.toml` when omitted.
 */
filePath?: string | null, expectedVersion?: string | null, };

export type ConfigEdit = { keyPath: string, value: JsonValue, mergeStrategy: MergeStrategy, };

export type ConfigLayer = { name: ConfigLayerSource, version: string, config: JsonValue, disabledReason: string | null, };

export type ConfigLayerMetadata = { name: ConfigLayerSource, version: string, };

export type ConfigLayerSource = { "type": "mdm", domain: string, key: string, } | { "type": "system", 
/**
 * This is the path to the system config.toml file, though it is not
 * guaranteed to exist.
 */
file: AbsolutePathBuf, } | { "type": "user", 
/**
 * This is the path to the user's config.toml file, though it is not
 * guaranteed to exist.
 */
file: AbsolutePathBuf, } | { "type": "project", dotCodexFolder: AbsolutePathBuf, } | { "type": "sessionFlags" } | { "type": "legacyManagedConfigTomlFromFile", file: AbsolutePathBuf, } | { "type": "legacyManagedConfigTomlFromMdm" };

export type ConfigReadParams = { includeLayers: boolean, 
/**
 * Optional working directory to resolve project config layers. If specified,
 * return the effective config as seen from that directory (i.e., including any
 * project layers between `cwd` and the project/repo root).
 */
cwd?: string | null, };

export type ConfigReadResponse = { config: Config, origins: { [key in string]?: ConfigLayerMetadata }, layers: Array<ConfigLayer> | null, };

export type ConfigRequirements = {allowedApprovalPolicies: Array<AskForApproval> | null, allowedSandboxModes: Array<SandboxMode> | null, allowedWebSearchModes: Array<WebSearchMode> | null, enforceResidency: ResidencyRequirement | null};

export type ConfigRequirementsReadResponse = { 
/**
 * Null if no requirements are configured (e.g. no requirements.toml/MDM entries).
 */
requirements: ConfigRequirements | null, };

export type ConfigValueWriteParams = { keyPath: string, value: JsonValue, mergeStrategy: MergeStrategy, 
/**
 * Path to the config file to write; defaults to the user's `config.toml` when omitted.
 */
filePath?: string | null, expectedVersion?: string | null, };

export type ConfigWarningNotification = { 
/**
 * Concise summary of the warning.
 */
summary: string, 
/**
 * Optional extra guidance or error details.
 */
details: string | null, 
/**
 * Optional path to the config file that triggered the warning.
 */
path?: string, 
/**
 * Optional range for the error location inside the config file.
 */
range?: TextRange, };

export type ConfigWriteResponse = { status: WriteStatus, version: string, 
/**
 * Canonical path to the config file that was written.
 */
filePath: AbsolutePathBuf, overriddenMetadata: OverriddenMetadata | null, };

/**
 * Deprecated: Use `ContextCompaction` item type instead.
 */
export type ContextCompactedNotification = { threadId: string, turnId: string, };

export type CreditsSnapshot = { hasCredits: boolean, unlimited: boolean, balance: string | null, };

export type DeprecationNoticeNotification = { 
/**
 * Concise summary of what is deprecated.
 */
summary: string, 
/**
 * Optional extra guidance, such as migration steps or rationale.
 */
details: string | null, };

export type DynamicToolCallOutputContentItem = { "type": "inputText", text: string, } | { "type": "inputImage", imageUrl: string, };

export type DynamicToolCallParams = { threadId: string, turnId: string, callId: string, tool: string, arguments: JsonValue, };

export type DynamicToolCallResponse = { contentItems: Array<DynamicToolCallOutputContentItem>, success: boolean, };

export type DynamicToolSpec = { name: string, description: string, inputSchema: JsonValue, };

export type ErrorNotification = { error: TurnError, willRetry: boolean, threadId: string, turnId: string, };

export type ExecPolicyAmendment = Array<string>;

export type ExperimentalFeature = { 
/**
 * Stable key used in config.toml and CLI flag toggles.
 */
name: string, 
/**
 * Lifecycle stage of this feature flag.
 */
stage: ExperimentalFeatureStage, 
/**
 * User-facing display name shown in the experimental features UI.
 * Null when this feature is not in beta.
 */
displayName: string | null, 
/**
 * Short summary describing what the feature does.
 * Null when this feature is not in beta.
 */
description: string | null, 
/**
 * Announcement copy shown to users when the feature is introduced.
 * Null when this feature is not in beta.
 */
announcement: string | null, 
/**
 * Whether this feature is currently enabled in the loaded config.
 */
enabled: boolean, 
/**
 * Whether this feature is enabled by default.
 */
defaultEnabled: boolean, };

export type ExperimentalFeatureListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null, };

export type ExperimentalFeatureListResponse = { data: Array<ExperimentalFeature>, 
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * If None, there are no more items to return.
 */
nextCursor: string | null, };

export type ExperimentalFeatureStage = "beta" | "underDevelopment" | "stable" | "deprecated" | "removed";

export type FeedbackUploadParams = { classification: string, reason?: string | null, threadId?: string | null, includeLogs: boolean, };

export type FeedbackUploadResponse = { threadId: string, };

export type FileChangeApprovalDecision = "accept" | "acceptForSession" | "decline" | "cancel";

export type FileChangeOutputDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, };

export type FileChangeRequestApprovalParams = { threadId: string, turnId: string, itemId: string, 
/**
 * Optional explanatory reason (e.g. request for extra write access).
 */
reason?: string | null, 
/**
 * [UNSTABLE] When set, the agent is asking the user to allow writes under this root
 * for the remainder of the session (unclear if this is honored today).
 */
grantRoot?: string | null, };

export type FileChangeRequestApprovalResponse = { decision: FileChangeApprovalDecision, };

export type FileUpdateChange = { path: string, kind: PatchChangeKind, diff: string, };

export type GetAccountParams = { 
/**
 * When `true`, requests a proactive token refresh before returning.
 *
 * In managed auth mode this triggers the normal refresh-token flow. In
 * external auth mode this flag is ignored. Clients should refresh tokens
 * themselves and call `account/login/start` with `chatgptAuthTokens`.
 */
refreshToken: boolean, };

export type GetAccountRateLimitsResponse = { 
/**
 * Backward-compatible single-bucket view; mirrors the historical payload.
 */
rateLimits: RateLimitSnapshot, 
/**
 * Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
 */
rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot } | null, };

export type GetAccountResponse = { account: Account | null, requiresOpenaiAuth: boolean, };

export type GitInfo = { sha: string | null, branch: string | null, originUrl: string | null, };

export type HazelnutScope = "example" | "workspace-shared" | "all-shared" | "personal";

export type ItemCompletedNotification = { item: ThreadItem, threadId: string, turnId: string, };

export type ItemStartedNotification = { item: ThreadItem, threadId: string, turnId: string, };

export type ListMcpServerStatusParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to a server-defined value.
 */
limit?: number | null, };

export type ListMcpServerStatusResponse = { data: Array<McpServerStatus>, 
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * If None, there are no more items to return.
 */
nextCursor: string | null, };

export type LoginAccountParams = { "type": "apiKey", apiKey: string, } | { "type": "chatgpt" } | { "type": "chatgptAuthTokens", 
/**
 * Access token (JWT) supplied by the client.
 * This token is used for backend API requests and email extraction.
 */
accessToken: string, 
/**
 * Workspace/account identifier supplied by the client.
 */
chatgptAccountId: string, 
/**
 * Optional plan type supplied by the client.
 *
 * When `null`, Codex attempts to derive the plan type from access-token
 * claims. If unavailable, the plan defaults to `unknown`.
 */
chatgptPlanType?: string | null, };

export type LoginAccountResponse = { "type": "apiKey", } | { "type": "chatgpt", loginId: string, 
/**
 * URL the client should open in a browser to initiate the OAuth flow.
 */
authUrl: string, } | { "type": "chatgptAuthTokens", };

export type LogoutAccountResponse = Record<string, never>;

export type McpAuthStatus = "unsupported" | "notLoggedIn" | "bearerToken" | "oAuth";

export type McpServerOauthLoginCompletedNotification = { name: string, success: boolean, error?: string, };

export type McpServerOauthLoginParams = { name: string, scopes?: Array<string> | null, timeoutSecs?: bigint | null, };

export type McpServerOauthLoginResponse = { authorizationUrl: string, };

export type McpServerRefreshResponse = Record<string, never>;

export type McpServerStatus = { name: string, tools: { [key in string]?: Tool }, resources: Array<Resource>, resourceTemplates: Array<ResourceTemplate>, authStatus: McpAuthStatus, };

export type McpToolCallError = { message: string, };

export type McpToolCallProgressNotification = { threadId: string, turnId: string, itemId: string, message: string, };

export type McpToolCallResult = { content: Array<JsonValue>, structuredContent: JsonValue | null, };

export type McpToolCallStatus = "inProgress" | "completed" | "failed";

export type MergeStrategy = "replace" | "upsert";

export type Model = { id: string, model: string, upgrade: string | null, displayName: string, description: string, hidden: boolean, supportedReasoningEfforts: Array<ReasoningEffortOption>, defaultReasoningEffort: ReasoningEffort, inputModalities: Array<InputModality>, supportsPersonality: boolean, isDefault: boolean, };

export type ModelListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null, 
/**
 * When true, include models that are hidden from the default picker list.
 */
includeHidden?: boolean | null, };

export type ModelListResponse = { data: Array<Model>, 
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * If None, there are no more items to return.
 */
nextCursor: string | null, };

export type ModelRerouteReason = "highRiskCyberActivity";

export type ModelReroutedNotification = { threadId: string, turnId: string, fromModel: string, toModel: string, reason: ModelRerouteReason, };

export type NetworkAccess = "restricted" | "enabled";

export type NetworkRequirements = { enabled: boolean | null, httpPort: number | null, socksPort: number | null, allowUpstreamProxy: boolean | null, dangerouslyAllowNonLoopbackProxy: boolean | null, dangerouslyAllowNonLoopbackAdmin: boolean | null, allowedDomains: Array<string> | null, deniedDomains: Array<string> | null, allowUnixSockets: Array<string> | null, allowLocalBinding: boolean | null, };

export type OverriddenMetadata = { message: string, overridingLayer: ConfigLayerMetadata, effectiveValue: JsonValue, };

export type PatchApplyStatus = "inProgress" | "completed" | "failed" | "declined";

export type PatchChangeKind = { "type": "add" } | { "type": "delete" } | { "type": "update", move_path: string | null, };

/**
 * EXPERIMENTAL - proposed plan streaming deltas for plan items. Clients should
 * not assume concatenated deltas match the completed plan item content.
 */
export type PlanDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, };

export type ProductSurface = "chatgpt" | "codex" | "api" | "atlas";

export type ProfileV2 = { model: string | null, model_provider: string | null, approval_policy: AskForApproval | null, model_reasoning_effort: ReasoningEffort | null, model_reasoning_summary: ReasoningSummary | null, model_verbosity: Verbosity | null, web_search: WebSearchMode | null, chatgpt_base_url: string | null, } & ({ [key in string]?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null });

export type RateLimitSnapshot = { limitId: string | null, limitName: string | null, primary: RateLimitWindow | null, secondary: RateLimitWindow | null, credits: CreditsSnapshot | null, planType: PlanType | null, };

export type RateLimitWindow = { usedPercent: number, windowDurationMins: number | null, resetsAt: number | null, };

export type RawResponseItemCompletedNotification = { threadId: string, turnId: string, item: ResponseItem, };

export type ReadOnlyAccess = { "type": "restricted", includePlatformDefaults: boolean, readableRoots: Array<AbsolutePathBuf>, } | { "type": "fullAccess" };

export type ReasoningEffortOption = { reasoningEffort: ReasoningEffort, description: string, };

export type ReasoningSummaryPartAddedNotification = { threadId: string, turnId: string, itemId: string, summaryIndex: number, };

export type ReasoningSummaryTextDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, summaryIndex: number, };

export type ReasoningTextDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, contentIndex: number, };

export type RemoteSkillSummary = { id: string, name: string, description: string, };

export type ResidencyRequirement = "us";

export type ReviewDelivery = "inline" | "detached";

export type ReviewStartParams = { threadId: string, target: ReviewTarget, 
/**
 * Where to run the review: inline (default) on the current thread or
 * detached on a new thread (returned in `reviewThreadId`).
 */
delivery?: ReviewDelivery | null, };

export type ReviewStartResponse = { turn: Turn, 
/**
 * Identifies the thread where the review runs.
 *
 * For inline reviews, this is the original thread id.
 * For detached reviews, this is the id of the new review thread.
 */
reviewThreadId: string, };

export type ReviewTarget = { "type": "uncommittedChanges" } | { "type": "baseBranch", branch: string, } | { "type": "commit", sha: string, 
/**
 * Optional human-readable label (e.g., commit subject) for UIs.
 */
title: string | null, } | { "type": "custom", instructions: string, };

export type SandboxMode = "read-only" | "workspace-write" | "danger-full-access";

export type SandboxPolicy = { "type": "dangerFullAccess" } | { "type": "readOnly", access: ReadOnlyAccess, } | { "type": "externalSandbox", networkAccess: NetworkAccess, } | { "type": "workspaceWrite", writableRoots: Array<AbsolutePathBuf>, readOnlyAccess: ReadOnlyAccess, networkAccess: boolean, excludeTmpdirEnvVar: boolean, excludeSlashTmp: boolean, };

export type SandboxWorkspaceWrite = { writable_roots: Array<string>, network_access: boolean, exclude_tmpdir_env_var: boolean, exclude_slash_tmp: boolean, };

export type SessionSource = "cli" | "vscode" | "exec" | "appServer" | { "subAgent": SubAgentSource } | "unknown";

export type SkillDependencies = { tools: Array<SkillToolDependency>, };

export type SkillErrorInfo = { path: string, message: string, };

export type SkillInterface = { displayName?: string, shortDescription?: string, iconSmall?: string, iconLarge?: string, brandColor?: string, defaultPrompt?: string, };

export type SkillMetadata = { name: string, description: string, 
/**
 * Legacy short_description from SKILL.md. Prefer SKILL.json interface.short_description.
 */
shortDescription?: string, interface?: SkillInterface, dependencies?: SkillDependencies, path: string, scope: SkillScope, enabled: boolean, };

export type SkillScope = "user" | "repo" | "system" | "admin";

export type SkillToolDependency = { type: string, value: string, description?: string, transport?: string, command?: string, url?: string, };

export type SkillsConfigWriteParams = { path: string, enabled: boolean, };

export type SkillsConfigWriteResponse = { effectiveEnabled: boolean, };

export type SkillsListEntry = { cwd: string, skills: Array<SkillMetadata>, errors: Array<SkillErrorInfo>, };

export type SkillsListExtraRootsForCwd = { cwd: string, extraUserRoots: Array<string>, };

export type SkillsListParams = { 
/**
 * When empty, defaults to the current session working directory.
 */
cwds?: Array<string>, 
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean, 
/**
 * Optional per-cwd extra roots to scan as user-scoped skills.
 */
perCwdExtraUserRoots?: Array<SkillsListExtraRootsForCwd> | null, };

export type SkillsListResponse = { data: Array<SkillsListEntry>, };

export type SkillsRemoteReadParams = { hazelnutScope: HazelnutScope, productSurface: ProductSurface, enabled: boolean, };

export type SkillsRemoteReadResponse = { data: Array<RemoteSkillSummary>, };

export type SkillsRemoteWriteParams = { hazelnutId: string, };

export type SkillsRemoteWriteResponse = { id: string, path: string, };

export type TerminalInteractionNotification = { threadId: string, turnId: string, itemId: string, processId: string, stdin: string, };

export type TextElement = { 
/**
 * Byte range in the parent `text` buffer that this element occupies.
 */
byteRange: ByteRange, 
/**
 * Optional human-readable placeholder for the element, displayed in the UI.
 */
placeholder: string | null, };

export type TextPosition = { 
/**
 * 1-based line number.
 */
line: number, 
/**
 * 1-based column number (in Unicode scalar values).
 */
column: number, };

export type TextRange = { start: TextPosition, end: TextPosition, };

export type Thread = { id: string, 
/**
 * Usually the first user message in the thread, if available.
 */
preview: string, 
/**
 * Model provider used for this thread (for example, 'openai').
 */
modelProvider: string, 
/**
 * Unix timestamp (in seconds) when the thread was created.
 */
createdAt: number, 
/**
 * Unix timestamp (in seconds) when the thread was last updated.
 */
updatedAt: number, 
/**
 * [UNSTABLE] Path to the thread on disk.
 */
path: string | null, 
/**
 * Working directory captured for the thread.
 */
cwd: string, 
/**
 * Version of the CLI that created the thread.
 */
cliVersion: string, 
/**
 * Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).
 */
source: SessionSource, 
/**
 * Optional Git metadata captured when the thread was created.
 */
gitInfo: GitInfo | null, 
/**
 * Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read`
 * (when `includeTurns` is true) responses.
 * For all other responses and notifications returning a Thread,
 * the turns field will be an empty list.
 */
turns: Array<Turn>, };

export type ThreadArchiveParams = { threadId: string, };

export type ThreadArchiveResponse = Record<string, never>;

export type ThreadArchivedNotification = { threadId: string, };

export type ThreadCompactStartParams = { threadId: string, };

export type ThreadCompactStartResponse = Record<string, never>;

/**
 * There are two ways to fork a thread:
 * 1. By thread_id: load the thread from disk by thread_id and fork it into a new thread.
 * 2. By path: load the thread from disk by path and fork it into a new thread.
 *
 * If using path, the thread_id param will be ignored.
 *
 * Prefer using thread_id whenever possible.
 */
export type ThreadForkParams = {threadId: string, /**
 * [UNSTABLE] Specify the rollout path to fork from.
 * If specified, the thread_id param will be ignored.
 */
path?: string | null, /**
 * Configuration overrides for the forked thread, if any.
 */
model?: string | null, modelProvider?: string | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, /**
 * If true, persist additional rollout EventMsg variants required to
 * reconstruct a richer thread history on subsequent resume/fork/read.
 */
persistExtendedHistory: boolean};

export type ThreadForkResponse = { thread: Thread, model: string, modelProvider: string, cwd: string, approvalPolicy: AskForApproval, sandbox: SandboxPolicy, reasoningEffort: ReasoningEffort | null, };

export type ThreadItem = { "type": "userMessage", id: string, content: Array<UserInput>, } | { "type": "agentMessage", id: string, text: string, } | { "type": "plan", id: string, text: string, } | { "type": "reasoning", id: string, summary: Array<string>, content: Array<string>, } | { "type": "commandExecution", id: string, 
/**
 * The command to be executed.
 */
command: string, 
/**
 * The command's working directory.
 */
cwd: string, 
/**
 * Identifier for the underlying PTY process (when available).
 */
processId: string | null, status: CommandExecutionStatus, 
/**
 * A best-effort parsing of the command to understand the action(s) it will perform.
 * This returns a list of CommandAction objects because a single shell command may
 * be composed of many commands piped together.
 */
commandActions: Array<CommandAction>, 
/**
 * The command's output, aggregated from stdout and stderr.
 */
aggregatedOutput: string | null, 
/**
 * The command's exit code.
 */
exitCode: number | null, 
/**
 * The duration of the command execution in milliseconds.
 */
durationMs: number | null, } | { "type": "fileChange", id: string, changes: Array<FileUpdateChange>, status: PatchApplyStatus, } | { "type": "mcpToolCall", id: string, server: string, tool: string, status: McpToolCallStatus, arguments: JsonValue, result: McpToolCallResult | null, error: McpToolCallError | null, 
/**
 * The duration of the MCP tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "collabAgentToolCall", 
/**
 * Unique identifier for this collab tool call.
 */
id: string, 
/**
 * Name of the collab tool that was invoked.
 */
tool: CollabAgentTool, 
/**
 * Current status of the collab tool call.
 */
status: CollabAgentToolCallStatus, 
/**
 * Thread ID of the agent issuing the collab request.
 */
senderThreadId: string, 
/**
 * Thread ID of the receiving agent, when applicable. In case of spawn operation,
 * this corresponds to the newly spawned agent.
 */
receiverThreadIds: Array<string>, 
/**
 * Prompt text sent as part of the collab tool call, when available.
 */
prompt: string | null, 
/**
 * Last known status of the target agents, when available.
 */
agentsStates: { [key in string]?: CollabAgentState }, } | { "type": "webSearch", id: string, query: string, action: WebSearchAction | null, } | { "type": "imageView", id: string, path: string, } | { "type": "enteredReviewMode", id: string, review: string, } | { "type": "exitedReviewMode", id: string, review: string, } | { "type": "contextCompaction", id: string, };

export type ThreadListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null, 
/**
 * Optional sort key; defaults to created_at.
 */
sortKey?: ThreadSortKey | null, 
/**
 * Optional provider filter; when set, only sessions recorded under these
 * providers are returned. When present but empty, includes all providers.
 */
modelProviders?: Array<string> | null, 
/**
 * Optional source filter; when set, only sessions from these source kinds
 * are returned. When omitted or empty, defaults to interactive sources.
 */
sourceKinds?: Array<ThreadSourceKind> | null, 
/**
 * Optional archived filter; when set to true, only archived threads are returned.
 * If false or null, only non-archived threads are returned.
 */
archived?: boolean | null, 
/**
 * Optional cwd filter; when set, only threads whose session cwd exactly
 * matches this path are returned.
 */
cwd?: string | null, };

export type ThreadListResponse = { data: Array<Thread>, 
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * if None, there are no more items to return.
 */
nextCursor: string | null, };

export type ThreadLoadedListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to no limit.
 */
limit?: number | null, };

export type ThreadLoadedListResponse = { 
/**
 * Thread ids for sessions currently loaded in memory.
 */
data: Array<string>, 
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * if None, there are no more items to return.
 */
nextCursor: string | null, };

export type ThreadNameUpdatedNotification = { threadId: string, threadName?: string, };

export type ThreadReadParams = { threadId: string, 
/**
 * When true, include turns and their items from rollout history.
 */
includeTurns: boolean, };

export type ThreadReadResponse = { thread: Thread, };

/**
 * There are three ways to resume a thread:
 * 1. By thread_id: load the thread from disk by thread_id and resume it.
 * 2. By history: instantiate the thread from memory and resume it.
 * 3. By path: load the thread from disk by path and resume it.
 *
 * The precedence is: history > path > thread_id.
 * If using history or path, the thread_id param will be ignored.
 *
 * Prefer using thread_id whenever possible.
 */
export type ThreadResumeParams = {threadId: string, /**
 * [UNSTABLE] FOR CODEX CLOUD - DO NOT USE.
 * If specified, the thread will be resumed with the provided history
 * instead of loaded from disk.
 */
history?: Array<ResponseItem> | null, /**
 * [UNSTABLE] Specify the rollout path to resume from.
 * If specified, the thread_id param will be ignored.
 */
path?: string | null, /**
 * Configuration overrides for the resumed thread, if any.
 */
model?: string | null, modelProvider?: string | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null, /**
 * If true, persist additional rollout EventMsg variants required to
 * reconstruct a richer thread history on subsequent resume/fork/read.
 */
persistExtendedHistory: boolean};

export type ThreadResumeResponse = { thread: Thread, model: string, modelProvider: string, cwd: string, approvalPolicy: AskForApproval, sandbox: SandboxPolicy, reasoningEffort: ReasoningEffort | null, };

export type ThreadRollbackParams = { threadId: string, 
/**
 * The number of turns to drop from the end of the thread. Must be >= 1.
 *
 * This only modifies the thread's history and does not revert local file changes
 * that have been made by the agent. Clients are responsible for reverting these changes.
 */
numTurns: number, };

export type ThreadRollbackResponse = { 
/**
 * The updated thread after applying the rollback, with `turns` populated.
 *
 * The ThreadItems stored in each Turn are lossy since we explicitly do not
 * persist all agent interactions, such as command executions. This is the same
 * behavior as `thread/resume`.
 */
thread: Thread, };

export type ThreadSetNameParams = { threadId: string, name: string, };

export type ThreadSetNameResponse = Record<string, never>;

export type ThreadSortKey = "created_at" | "updated_at";

export type ThreadSourceKind = "cli" | "vscode" | "exec" | "appServer" | "subAgent" | "subAgentReview" | "subAgentCompact" | "subAgentThreadSpawn" | "subAgentOther" | "unknown";

export type ThreadStartParams = {model?: string | null, modelProvider?: string | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null, ephemeral?: boolean | null, /**
 * If true, opt into emitting raw Responses API items on the event stream.
 * This is for internal use only (e.g. Codex Cloud).
 */
experimentalRawEvents: boolean, /**
 * If true, persist additional rollout EventMsg variants required to
 * reconstruct a richer thread history on resume/fork/read.
 */
persistExtendedHistory: boolean};

export type ThreadStartResponse = { thread: Thread, model: string, modelProvider: string, cwd: string, approvalPolicy: AskForApproval, sandbox: SandboxPolicy, reasoningEffort: ReasoningEffort | null, };

export type ThreadStartedNotification = { thread: Thread, };

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, modelContextWindow: number | null, };

export type ThreadTokenUsageUpdatedNotification = { threadId: string, turnId: string, tokenUsage: ThreadTokenUsage, };

export type ThreadUnarchiveParams = { threadId: string, };

export type ThreadUnarchiveResponse = { thread: Thread, };

export type ThreadUnarchivedNotification = { threadId: string, };

export type TokenUsageBreakdown = { totalTokens: number, inputTokens: number, cachedInputTokens: number, outputTokens: number, reasoningOutputTokens: number, };

/**
 * EXPERIMENTAL. Captures a user's answer to a request_user_input question.
 */
export type ToolRequestUserInputAnswer = { answers: Array<string>, };

/**
 * EXPERIMENTAL. Defines a single selectable option for request_user_input.
 */
export type ToolRequestUserInputOption = { label: string, description: string, };

/**
 * EXPERIMENTAL. Params sent with a request_user_input event.
 */
export type ToolRequestUserInputParams = { threadId: string, turnId: string, itemId: string, questions: Array<ToolRequestUserInputQuestion>, };

/**
 * EXPERIMENTAL. Represents one request_user_input question and its required options.
 */
export type ToolRequestUserInputQuestion = { id: string, header: string, question: string, isOther: boolean, isSecret: boolean, options: Array<ToolRequestUserInputOption> | null, };

/**
 * EXPERIMENTAL. Response payload mapping question ids to answers.
 */
export type ToolRequestUserInputResponse = { answers: { [key in string]?: ToolRequestUserInputAnswer }, };

export type ToolsV2 = { web_search: boolean | null, view_image: boolean | null, };

export type Turn = { id: string, 
/**
 * Only populated on a `thread/resume` or `thread/fork` response.
 * For all other responses and notifications returning a Turn,
 * the items field will be an empty list.
 */
items: Array<ThreadItem>, status: TurnStatus, 
/**
 * Only populated when the Turn's status is failed.
 */
error: TurnError | null, };

export type TurnCompletedNotification = { threadId: string, turn: Turn, };

/**
 * Notification that the turn-level unified diff has changed.
 * Contains the latest aggregated diff across all file changes in the turn.
 */
export type TurnDiffUpdatedNotification = { threadId: string, turnId: string, diff: string, };

export type TurnError = { message: string, codexErrorInfo: CodexErrorInfo | null, additionalDetails: string | null, };

export type TurnInterruptParams = { threadId: string, turnId: string, };

export type TurnInterruptResponse = Record<string, never>;

export type TurnPlanStep = { step: string, status: TurnPlanStepStatus, };

export type TurnPlanStepStatus = "pending" | "inProgress" | "completed";

export type TurnPlanUpdatedNotification = { threadId: string, turnId: string, explanation: string | null, plan: Array<TurnPlanStep>, };

export type TurnStartParams = {threadId: string, input: Array<UserInput>, /**
 * Override the working directory for this turn and subsequent turns.
 */
cwd?: string | null, /**
 * Override the approval policy for this turn and subsequent turns.
 */
approvalPolicy?: AskForApproval | null, /**
 * Override the sandbox policy for this turn and subsequent turns.
 */
sandboxPolicy?: SandboxPolicy | null, /**
 * Override the model for this turn and subsequent turns.
 */
model?: string | null, /**
 * Override the reasoning effort for this turn and subsequent turns.
 */
effort?: ReasoningEffort | null, /**
 * Override the reasoning summary for this turn and subsequent turns.
 */
summary?: ReasoningSummary | null, /**
 * Override the personality for this turn and subsequent turns.
 */
personality?: Personality | null, /**
 * Optional JSON Schema used to constrain the final assistant message for this turn.
 */
outputSchema?: JsonValue | null, /**
 * EXPERIMENTAL - Set a pre-set collaboration mode.
 * Takes precedence over model, reasoning_effort, and developer instructions if set.
 *
 * For `collaboration_mode.settings.developer_instructions`, `null` means
 * "use the built-in instructions for the selected mode".
 */
collaborationMode?: CollaborationMode | null};

export type TurnStartResponse = { turn: Turn, };

export type TurnStartedNotification = { threadId: string, turn: Turn, };

export type TurnStatus = "completed" | "interrupted" | "failed" | "inProgress";

export type TurnSteerParams = { threadId: string, input: Array<UserInput>, 
/**
 * Required active turn id precondition. The request fails when it does not
 * match the currently active turn.
 */
expectedTurnId: string, };

export type TurnSteerResponse = { turnId: string, };

export type UserInput = { "type": "text", text: string, 
/**
 * UI-defined spans within `text` used to render or persist special elements.
 */
text_elements: Array<TextElement>, } | { "type": "image", url: string, } | { "type": "localImage", path: string, } | { "type": "skill", name: string, path: string, } | { "type": "mention", name: string, path: string, };

export type WebSearchAction = { "type": "search", query: string | null, queries: Array<string> | null, } | { "type": "openPage", url: string | null, } | { "type": "findInPage", url: string | null, pattern: string | null, } | { "type": "other" };

export type WindowsWorldWritableWarningNotification = { samplePaths: Array<string>, extraCount: number, failedScan: boolean, };

export type WriteStatus = "ok" | "okOverridden";